names:
- boneanomaly  #0
- bonelesion   #1
- foreignbody  #2
- fracture     #3
- metal        #4
- periostealreaction  #5
- pronatorsign        #6
- softtissue          #7
- text                #8
nc: 9                                # 类别数量
path: D:/pythonProject/ultralytics-main/GRAZPEDWRI-DX/data  # 数据集根目录
train: images/train                  # 训练集图像路径
val: images/valid                    # 验证集图像路径
test: images/test                    # 测试集图像路径

